services:
  jupyterlab: 
    image: zgrayblue/contrans2023
    env_file:
      - .env
    ports: 
      - "8889:8888"
    volumes: 
      - ./:/contrans2023
      - ./settings.txt:/root/.jupyter/lab/user-settings/@jupyterlab/notebook-extension/tracker.jupyterlab-settings
    networks:
      - dbnetwork

  postgres:
    image: postgres:latest
    env_file: 
      - .env 
    ports: 
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - dbnetwork

volumes:
  postgresdata:

networks:
  dbnetwork: